<?php

/**
 * @file
 * Primary module hooks for hello_world_by_drush module.
 */

use \Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function hello_world_by_drush_help($route_name, RouteMatchInterface $route_match) {
	switch ($route_name) {
		case 'help.page.hello_world_by_drush':
			$output = '';
			$output .= '<h3>' . t('About') . '</h3>';
			$output .= '<p>' . t('This is an example module.') . '</p>';
			return $output;
		default;
	}
}