# Schema for the configuration files of the Hello world by drush module.
hello_world_by_drush.settings:
  type: config_object
  label: 'Hello world by drush settings'
  mapping:
    example:
      type: string
      label: 'Example'
